#!/bin/bash
########################################################################
# 位置: /etc/init.d/halt
#
# 作用:硬件脚本
#
# 原作者:Gerard Beekmans - gerard@linuxfromscratch.org
#
# 版本: 00.00
#
# 说明:此文件为弦歌Linux专用，修改至CLFS脚本，如有问题请联系josnk.echo@gmail.com或swordhui@hotmail.com
# 备注:
########################################################################
. /etc/sysconfig/rc
. ${rc_functions}

case "${1}" in
	stop)
		halt -d -f -i -p
		;;
	*)
		echo "Usage: {stop}"
		exit 1
		;;
esac

# End $rc_base/init.d/halt
