#!/bin/bash
########################################################################
# 位置: /etc/init.d/localnet
#
# 作用:回环设备
#
# 原作者: Gerard Beekmans  - gerard@linuxfromscratch.org
#
# 版本: 00.00
#
# 说明:此文件为弦歌Linux专用，修改至CLFS脚本，如有问题请联系josnk.echo@gmail.com或swordhui@hotmail.com
# 备注:
########################################################################
. /etc/sysconfig/rc
. ${rc_functions}
. /etc/sysconfig/network

case "${1}" in
	start)
		boot_mesg "Bringing up the loopback interface..."
		ip addr add 127.0.0.1/8 label lo dev lo
		ip link set lo up
		evaluate_retval

		boot_mesg "Setting hostname to ${HOSTNAME}..."
		hostname ${HOSTNAME}
		evaluate_retval
		;;

	stop)
		boot_mesg "Bringing down the loopback interface..."
		ip link set lo down
		evaluate_retval
		;;

	restart)
		${0} stop
		sleep 1
		${0} start
		;;

	status)
		echo "Hostname is: $(hostname)"
		ip link show lo
		;;

	*)
		echo "Usage: ${0} {start|stop|restart|status}"
		exit 1
		;;
esac

# End $rc_base/init.d/localnet
