#!/bin/bash
########################################################################
# 位置: /etc/init.d/mountfs
#
# 作用:加载proc和sysfs文件系统
#
# 原作者:Gerard Beekmans - gerard@linuxfromscratch.org
#
# 版本: 00.00
#
# 说明:此文件为弦歌Linux专用，修改至CLFS脚本，如有问题请联系josnk.echo@gmail.com或swordhui@hotmail.com
# 备注:
########################################################################
. /etc/sysconfig/rc
. ${rc_functions}

case "${1}" in
	start)
		boot_mesg -n "Mounting kernel-based file systems:" ${INFO}

		if ! mountpoint /proc >/dev/null; then
			boot_mesg -n " /proc" ${NORMAL}
			mount -n /proc || failed=1
		fi

		if ! mountpoint /sys >/dev/null; then
			boot_mesg -n " /sys" ${NORMAL}
			mount -n /sys || failed=1
		fi

		boot_mesg "" ${NORMAL}

		(exit ${failed})
		evaluate_retval
		;;

	*)
		echo "Usage: ${0} {start}"
		exit 1
		;;
esac

# End $rc_base/init.d/mountkernfs
