#!/bin/bash
########################################################################
# 位置: /etc/init.d/mountfs
#
# 作用:文件系统加载脚本
#
# 原作者:Gerard Beekmans - gerard@linuxfromscratch.org
#
# 版本: 00.00
#
# 说明:此文件为弦歌Linux专用，修改至CLFS脚本，如有问题请联系josnk.echo@gmail.com或swordhui@hotmail.com
# 备注:
########################################################################
. /etc/sysconfig/rc
. ${rc_functions}

case "${1}" in
	start)
		boot_mesg "Remounting root file system in read-write mode..."
		mount -n -o remount,rw / >/dev/null
		evaluate_retval

		# Remove fsck-related file system watermarks.
		rm -f /fastboot /forcefsck

		boot_mesg "Recording existing mounts in /etc/mtab..."
		> /etc/mtab
		mount -f / || failed=1
		mount -f /proc || failed=1
		mount -f /sys || failed=1
		(exit ${failed})
		evaluate_retval

		# This will mount all filesystems that do not have _netdev in
		# their option list.  _netdev denotes a network filesystem.
		boot_mesg "Mounting remaining file systems..."
		mount -a -O no_netdev >/dev/null
		evaluate_retval
		;;

	stop)
		boot_mesg "Unmounting all other currently mounted file systems..."
		umount -a -d -r >/dev/null
		evaluate_retval
		;;

	*)
		echo "Usage: ${0} {start|stop}"
		exit 1
		;;
esac

# End $rc_base/init.d/mountfs
