#!/bin/bash
########################################################################
# 位置: /etc/init.d/sysklogd
#
# 作用:系统及内核控制日志脚本
#
# 原作者:Gerard Beekmans  - gerard@linuxfromscratch.org
#
# 版本: 00.00
#
# 说明:此文件为弦歌Linux专用，修改至CLFS脚本，如有问题请联系josnk.echo@gmail.com或swordhui@hotmail.com
# 备注:
########################################################################
. /etc/sysconfig/rc
. ${rc_functions}

case "${1}" in
	start)
		boot_mesg "Starting system log daemon..."
		loadproc rsyslogd -c3
		;;


	stop)
		boot_mesg "Stopping system log daemon..."
		killproc rsyslogd
		;;

	reload)
		boot_mesg "Reloading system log daemon config file..."
		reloadproc rsyslogd
		;;

	restart)
		${0} stop
		sleep 1
		${0} start
		;;

	status)
		statusproc syslogd
		;;

	*)
		echo "Usage: ${0} {start|stop|reload|restart|status}"
		exit 1
		;;
esac

# End $rc_base/init.d/sysklogd
