#!/bin/bash
########################################################################
# 位置: /etc/init.d/sendsignals
#
# 作用:Sendsignals Script
#
# 原作者:Gerard Beekmans  - gerard@linuxfromscratch.org
#
# 版本: 00.00
#
# 说明:此文件为弦歌Linux专用，修改至CLFS脚本，如有问题请联系josnk.echo@gmail.com或swordhui@hotmail.com
# 备注:
########################################################################
. /etc/sysconfig/rc
. ${rc_functions}

case "${1}" in
	stop)
		boot_mesg "Sending all processes the TERM signal..."
		killall5 -15
		error_value=${?}

		sleep ${KILLDELAY}

		if [ "${error_value}" = 0 ]; then
			echo_ok
		else
			echo_failure
		fi

		boot_mesg "Sending all processes the KILL signal..."
		killall5 -9
		error_value=${?}

		sleep ${KILLDELAY}

		if [ "${error_value}" = 0 ]; then
			echo_ok
		else
			echo_failure
		fi
		;;

	*)
		echo "Usage: ${0} {stop}"
		exit 1
		;;

esac

# End $rc_base/init.d/sendsignals
