#!/bin/bash
########################################################################
# 位置: /etc/init.d/setclock
#
# 作用:设置系统时间脚本
#
# 原作者:Gerard Beekmans  - gerard@linuxfromscratch.org
#
# 版本: 00.00
#
# 说明:此文件为弦歌Linux专用，修改至CLFS脚本，如有问题请联系josnk.echo@gmail.com或swordhui@hotmail.com
# 备注:
########################################################################
. /etc/sysconfig/rc
. ${rc_functions}
. /etc/sysconfig/clock

CLOCKPARAMS=

case "${UTC}" in
	yes|true|1)
		CLOCKPARAMS="${CLOCKPARAMS} --utc"
		;;

	no|false|0)
		CLOCKPARAMS="${CLOCKPARAMS} --localtime"
		;;

esac

case ${1} in
	start)
		boot_mesg "Setting system clock..."
		hwclock --hctosys ${CLOCKPARAMS} >/dev/null
		evaluate_retval
		;;

	stop)
		boot_mesg "Setting hardware clock..."
		hwclock --systohc ${CLOCKPARAMS} >/dev/null
		evaluate_retval
		;;

	*)
		echo "Usage: ${0} {start|stop}"
		;;

esac
