#!/bin/bash
########################################################################
# 位置: /etc/init.d/swap
#
# 作用:swap控制脚本
#
# 原作者:Gerard Beekmans  - gerard@linuxfromscratch.org
#
# 版本: 00.00
#
# 说明:此文件为弦歌Linux专用，修改至CLFS脚本，如有问题请联系josnk.echo@gmail.com或swordhui@hotmail.com
# 备注:
########################################################################
. /etc/sysconfig/rc
. ${rc_functions}

case "${1}" in
	start)
		boot_mesg "Activating all swap files/partitions..."
		swapon -a
		evaluate_retval
		;;

	stop)
		boot_mesg "Deactivating all swap files/partitions..."
		swapoff -a
		evaluate_retval
		;;

	restart)
		${0} stop
		sleep 1
		${0} start
		;;

	status)
		boot_mesg "Retrieving swap status." ${INFO}
		echo_ok
		echo
		swapon -s
		;;

	*)
		echo "Usage: ${0} {start|stop|restart|status}"
		exit 1
		;;
esac

# End $rc_base/init.d/swap
