#!/bin/bash
########################################################################
# 位置: /etc/init.d/sysctl
#
# 作用:系统微调脚本
#
# 原作者: Nathan Coulson (nathan@linuxfromscratch.org)
#         Matthew Burgress (matthew@linuxfromscratch.org)
#
# 版本: 00.00
#
# 说明:此文件为弦歌Linux专用，修改至CLFS脚本，如有问题请联系josnk.echo@gmail.com或swordhui@hotmail.com
# 备注:需要配置/etc/sysctl.conf文件，慎用。
########################################################################
. /etc/sysconfig/rc
. ${rc_functions}

case "${1}" in
	start)
		if [ -f "/etc/sysctl.conf" ]; then
			boot_mesg "Setting kernel runtime parameters..."
			sysctl -q -p
			evaluate_retval
		fi
		;;

	status)
		sysctl -a	
		;;

	*)
		echo "Usage: ${0} {start|status}"
		exit 1
		;;
esac

# End $rc_base/init.d/sysctl
