#!/bin/bash
########################################################################
# 位置: /etc/init.d/
#
# 作用:启动脚本模板文件
#
# 原作者: 
#
# 版本: 00.00
#
# 说明:此文件为弦歌Linux专用，修改至CLFS脚本，如有问题请联系josnk.echo@gmail.com或swordhui@hotmail.com
# 备注:
########################################################################
. /etc/sysconfig/rc
. ${rc_functions}

case "${1}" in
	start)
		boot_mesg "Starting..."
		loadproc
		;;

	stop)
		boot_mesg "Stopping..."
		killproc
		;;

	reload)
		boot_mesg "Reloading..."
		reloadproc
		;;

	restart)
		${0} stop
		sleep 1
		${0} start
		;;

	status)
		statusproc
		;;

	*)
		echo "Usage: ${0} {start|stop|reload|restart|status}"
		exit 1
		;;
esac

# End $rc_base/init.d/
