#!/bin/bash
########################################################################
# 位置: /etc/init.d/udev
#
# 作用:Udev设备启动脚本
#
# 原作者:  Based on Open Suse Udev Rules
#          kay.sievers@suse.de
#
# Adapted to  : Jim Gifford
# LFS	      : Alexander E. Patrakov
# 版本: 00.00
#
# 说明:此文件为弦歌Linux专用，修改至CLFS脚本，如有问题请联系josnk.echo@gmail.com或swordhui@hotmail.com
# 备注:
########################################################################
. /etc/sysconfig/rc
. ${rc_functions}

case "$1" in
    start)
	boot_mesg "Creating /dev in tmpfs..."
	mount -n -t tmpfs -o mode=0755 udev /dev
	evaluate_retval

	boot_mesg "Copying static entries..."
	cp --preserve=all --recursive --remove-destination /lib/udev/devices/* /dev
	evaluate_retval
	
	boot_mesg "Setting Permissons on /dev/shm..."
	chmod 1777 /dev/shm
	evaluate_retval

	echo "" > /sys/kernel/uevent_helper

	# start udevd
	boot_mesg "Starting udevd..."
	/sbin/udevd --daemon
	evaluate_retval

	# start coldplugging
	boot_mesg "Performing Coldplugging..."

	# unlikely, but we may be faster than the first event
	mkdir -p /dev/.udev/queue

	# configure all devices
	/sbin/udevadm trigger
	
	# this replaces the old loop, exits after all devices are done
	/sbin/udevadm settle

	echo_ok
	;;

    stop)
	boot_mesg "Stopping udevd..."
	killproc /sbin/udevd
	;;

    restart)
	boot_mesg "Restarting udevd..."
	killproc /sbin/udevd
	loadproc /sbin/udevd --daemon
	evaluate_retval
	;;

    status)
	statusproc /sbin/udevd
	;;

    reload)
	boot_mesg "Reloading udev rules..."
	udevadm control reload_rules
	cp --preserve=all --recursive --update /lib/udev/devices/* /dev
	evaluate_retval
	;;

    force-reload)
	boot_mesg "Updating all available device nodes in /dev..."
	udevadm control reload_rules
	rm -rf /dev/.udev /dev/disk
	cp --preserve=all --recursive --update /lib/udev/devices/* /dev
	/sbin/udevadm trigger
	/sbin/udevadm settle
	evaluate_retval
	;;

    *)
	echo "Usage: $0 {start|stop|restart|status|reload|force-reload}"
	exit 1
	;;
esac
